#autologin
---
- name: Create /etc/systemd/system/getty@tty1.service.d directory.
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory

- name: Create autologin service.
  blockinfile:
    path: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    create: true
    block: |
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty -o '-p -f -- \\u' --noclear --autologin arcade %I $TERM && /usr/local/bin/mymenu

- name: Remove ansible text.
  lineinfile:
    dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    state: absent
    regexp: "ANSIBLE"

- name: Copy configurator executable.
  copy:
    src: "{{ role_path }}/files/usr/local/bin/configurator"
    dest: "/usr/local/bin/configurator"
    mode: 0755

- name: Copy configurator service.
  copy:
    src: "{{ role_path }}/files/etc/systemd/system/configurator.service"
    dest: "/etc/systemd/system/configurator.service"
    mode: 0644

- name: Enable configurator service.
  file:
    src: "/etc/systemd/system/configurator.service"
    dest: "/etc/systemd/system/multi-user.target.wants/configurator.service"
    state: link

- name: Copy autolauncher.
  copy:
    src: "{{ role_path }}/files/etc/profile.d/99-launcher.sh"
    dest: "/etc/profile.d/99-launcher.sh"
    mode: 0644

