#autologin
---
- name: Create /etc/systemd/system/getty@tty1.service.d directory.
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory

- name: Create autologin service.
  blockinfile:
    path: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    create: true
    block: |
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty -o '-p -f -- \\u' --noclear --autologin arcade %I $TERM

- name: Remove ansible text.
  lineinfile:
    dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    state: absent
    regexp: "ANSIBLE"

- name: Copy autolauncher.
  copy:
    src: "{{ role_path }}/files/etc/profile.d/99-launcher.sh"
    dest: "/etc/profile.d/99-launcher.sh"
    mode: 0644

