#Install firmwares, disable speaker and enable audio
---
- name: Install extra firmwares.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - firmware-linux-nonfree
    - firmware-misc-nonfree
    - firmware-sof-signed
    - firmware-intel-sound
  when: ansible_distribution == 'Debian'

- name: Install openssh-server.
  apt:
    name: "openssh-server"

- name: Install audio utils.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - alsa-utils
    - pulseaudio
    - pipewire

- name: Copy listconnectors script.
  copy:
    src: "{{ role_path }}/files/usr/local/bin/listconnectors"
    dest: "/usr/local/bin/listconnectors"
    mode: 0755

- name: Disable pcspeaker.
  lineinfile:
    create: yes
    path: "/etc/modprobe.d/nobeep.conf"
    line: "blacklist pcspkr"

- name: Disable pcspeaker
  replace:
    dest: "/etc/inputrc"
    regexp: "# set bell-style none"
    replace: "set bell-style none"
