#creates new user. username and password are "arcade"
#use 'mkpasswd --method=sha-512' to create password (whois program).
---
  - name: Install extra packages.
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - sudo
      - xz-utils

  - name: Create arcade user. Debian.
    user:
       name: arcade
       password: $6$ndekHMDnVv4Fdr6B$CD1ZtFjKS7loAjnY/j7NYnw05Sdd3yNeKXwNMI4zRsQo1vRisinuHkMbKoy0T84G3/G.ky1kM9frooS.Argc81
       shell: /bin/bash
       groups: cdrom,floppy,audio,dip,video,plugdev,netdev,sudo,render,input
    register: arcade
    when: ansible_distribution == 'Debian'

  - name: Create arcade user. Ubuntu.
    user:
       name: arcade
       password: $6$ndekHMDnVv4Fdr6B$CD1ZtFjKS7loAjnY/j7NYnw05Sdd3yNeKXwNMI4zRsQo1vRisinuHkMbKoy0T84G3/G.ky1kM9frooS.Argc81
       shell: /bin/bash
       groups: adm,cdrom,dip,plugdev,sudo,render
    register: arcade
    when: ansible_distribution == 'Ubuntu'

  - name: Arcade user doesn't need password for sudo.
    blockinfile:
      dest: "/etc/sudoers.d/arcade"
      create: yes
      block: |
        arcade ALL=(ALL) NOPASSWD: ALL
