#dialog menu
---
- name: Install xorg and openbox.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - xorg
    - openbox

- name: Create openbox configuration dir.
  file:
    path: "/home/arcade/.config/openbox"
    state: directory
    owner: arcade
    group: arcade

- name: Autolaunch retroarch with openbox.
  copy:
    src: "{{ role_path }}/files/etc/xdg/openbox/autostart"
    dest: "/home/arcade/.config/openbox/autostart"
    owner: arcade
    group: arcade
    mode: 0644
