#Install kernel and configure grub
---
- name: Check 15khz kernels.
  find:
    paths:
      - "/boot"
    patterns:
      - "*15khz*"
  register: result

- name: Download kernel debs. 64 bit.
  get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dest }}"
    timeout: 60
  with_items:
     - { src: "https://github.com/Ronbinn/retrodebiankms/releases/download/23_12_2024/linux-image-6.6.65-15khz_6.6.65-1_amd64.deb", dest: "/root/linux_image.deb" }
     - { src: "https://github.com/Ronbinn/retrodebiankms/releases/download/23_12_2024/linux-headers-6.6.65-15khz_6.6.65-1_amd64.deb", dest: "/root/linux_headers.deb" }
     - { src: "https://github.com/Ronbinn/retrodebiankms/releases/download/23_12_2024/linux-libc-dev_6.6.65-1_amd64.deb", dest: "/root/linux_libc.deb" }
  when:
    - ansible_architecture == 'x86_64'
    - result.matched == 0

- name: Download kernel debs. 32 bit.
  get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dest }}"
    timeout: 60
  with_items:
     - { src: "https://github.com/Ronbinn/retrodebiankms/releases/download/23_12_2024/linux-image-6.6.65-15khz_6.6.65-1_i386.deb", dest: "/root/linux_image.deb" }
     - { src: "https://github.com/Ronbinn/retrodebiankms/releases/download/23_12_2024/linux-headers-6.6.65-15khz_6.6.65-1_i386.deb", dest: "/root/linux_headers.deb" }
     - { src: "https://github.com/Ronbinn/retrodebiankms/releases/download/23_12_2024/linux-libc-dev_6.6.65-1_i386.deb", dest: "/root/linux_libc.deb" }
  when:
    - ansible_architecture == 'i386'
    - result.matched == 0

- name: Install 15khz kernel debs.
  apt:
    deb: "{{ item }}"
  with_items:
    - "/root/linux_image.deb"
    - "/root/linux_headers.deb"
    - "/root/linux_libc.deb"
  when: result.matched == 0

- name: Remove deb files.
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/root/linux_image.deb"
    - "/root/linux_headers.deb"
    - "/root/linux_libc.deb"
  when: result.matched == 0

- name: Find new kernel's initrd.
  find:
    paths:
      - "/boot"
    patterns:
      - "initrd*15khz*"
  register: initrd15

- name: Find new kernel's vmlinuz.
  find:
    paths:
      - "/boot"
    patterns:
      - "vmlinuz*15khz*"
  register: vmlinuz15

- name: Create new links. Debian.
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
     - { src: "{{ initrd15.files[-1].path | replace('/boot','boot') }}", dest: "/initrd.img" } #0 is first -1 is last
     - { src: "{{ vmlinuz15.files[-1].path | replace('/boot','boot') }}", dest: "/vmlinuz" } #remove first slash
  when: ansible_distribution == 'Debian'

- name: Create new links. Ubuntu.
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
     - { src: "{{ initrd15.files[-1].path }}", dest: "/boot/initrd.img" }
     - { src: "{{ vmlinuz15.files[-1].path }}", dest: "/boot/vmlinuz" }
  when: ansible_distribution == 'Ubuntu'

- name: Modify grub default line.
  lineinfile:
    dest: /etc/default/grub
    regexp: '^(.*)GRUB_CMDLINE_LINUX_DEFAULT=(.*)$'
#    line: 'GRUB_CMDLINE_LINUX_DEFAULT="video=VGA-1:1280x480iec"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="video=1280x480iS"'

- name: Modify grub timeout.
  lineinfile:
    dest: /etc/default/grub
    regexp: '^(.*)GRUB_TIMEOUT=(.*)$'
    line: 'GRUB_TIMEOUT=2'

- name: Uninstall old kernel.
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
     - linux-image-686-pae
     - linux-image-amd64
     - linux-image-generic
