#install and configure es-de
---
- name: Install dependencies.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libcurl4
    - libfreeimage3
    - libgit2-1.5
    - libpugixml1v5
    - libsdl2-2.0-0
    - libavcodec59
    - libavfilter8
    - libopengl0
    - libegl1

- name: Check if exists a emulationstation_de installation.
  stat:
    path: "/usr/local/bin/es-de"
  register: bin

- name: Download emulationstation_de. 64 bit.
  get_url:
    url: "https://github.com/Ronbinn/retrodebiankms/releases/download/23_12_2024/emulationstation_de_v3.1.1_amd64.deb"
    dest: "/home/emulationstation_de.deb"
    timeout: 60
  when:
    - bin.stat.exists == false
    - ansible_architecture == 'x86_64'

- name: Download emulationstation_de. 32 bit.
  get_url:
    url: "https://github.com/Ronbinn/retrodebiankms/releases/download/23_12_2024/emulationstation_de_v3.1.1_i386.deb"
    dest: "/home/emulationstation_de.deb"
    timeout: 60
  when:
    - bin.stat.exists == false
    - ansible_architecture == 'i386'

- name: Install emulationstation_de.
  apt:
    deb: "/home/emulationstation_de.deb"
  when: bin.stat.exists == false

- name: Remove deb file.
  file:
    path: "/home/emulationstation_de.deb"
    state: absent

- name: Check if simplemenu theme is installed.
  stat:
    path: "/usr/local/share/es-de/themes/simplemenu-es-de"
  register: theme

- name: Install git.
  apt:
    name: "git"
  when: theme.stat.exists == false

- name: Download themes.
  git:
    repo: "{{ item.url }}"
    dest: "{{ item.dest }}"
  with_items:
    - { url: "https://github.com/Rose22/simplemenu-es-de", dest: "/usr/local/share/es-de/themes/simplemenu-es-de" }
    - { url: "https://github.com/anthonycaccese/mister-menu-es-de", dest: "/usr/local/share/es-de/themes/mister-menu-es-de" }
  when: theme.stat.exists == false

- name: Uninstall git.
  apt:
    name: "git"
    state: absent
  when: theme.stat.exists == false

- name: Create ROMs dir.
  command:
    argv:
      - "/usr/local/bin/es-de"
      - "--create-system-dirs"
      - "--home"
      - "/home/arcade"

- name: Create config dirs.
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/home/arcade/ES-DE/settings"
    - "/home/arcade/ES-DE/gamelists/arcade"

- name: Copy config files.
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/home/arcade/{{ item }}"
    mode: 0644
  with_items:
    - "ES-DE/settings/es_settings.xml"
    - "ES-DE/gamelists/arcade/gamelist.xml"

- name: Change file ownership.
  file:
   dest: "{{ item }}"
   owner: arcade
   group: arcade
   mode: u=rwX,g=rX,o=rX
   recurse: yes
  with_items:
    - "/home/arcade/ROMs"
    - "/home/arcade/ES-DE"

- name: Copy launcher.
  copy:
    src: "{{ role_path }}/files/usr/local/bin/myesde"
    dest: "/usr/local/bin/myesde"
    mode: 0755

- name: Copy rom.
  copy:
    src: "{{ role_path }}/files/wrally.zip"
    dest: "/home/arcade/ROMs/arcade/wrally.zip"
    mode: 0644
