---
- name: Install dependencies.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libfreeimage3
    - libsdl2-2.0-0
    - libcurl4
    - libvlc5
    - libgl1

- name: Check if exists a emulationstation installation.
  stat:
    path: "/usr/local/bin/emulationstation"
  register: bin

- name: Download emulationstation. 64 bit.
  get_url:
    url: "https://www.dropbox.com/scl/fi/6poaamcn1rwwdu4xysbrw/emulationstation_v2.11.2_amd64.deb?rlkey=v637bpqkylc32j8p7ot4i1bf9&st=pyxk67ta&dl=1"
    dest: "/home/emulationstation.deb"
  when:
    - bin.stat.exists == false
    - ansible_architecture == 'x86_64'

- name: Download emulationstation. 32 bit.
  get_url:
    url: "https://www.dropbox.com/scl/fi/ffs5kg1y8z62vcddrtbg0/emulationstation_v2.11.2_i386.deb?rlkey=s09g19iqwcbx9b6hqppkqenjn&st=b8tof3dl&dl=1"
    dest: "/home/emulationstation.deb"
  when:
    - bin.stat.exists == false
    - ansible_architecture == 'i386'

- name: Install emulationstation.
  apt:
    deb: "/home/emulationstation.deb"
  when: bin.stat.exists == false

- name: Remove deb file.
  file:
    path: "/home/emulationstation.deb"
    state: absent
