#install and configure groovymame
---
- name: Install original MAME to get the dependencies.
  apt:
    name: mame

- name: Install libdrm-dev and xorg-dev.
  apt:
    name: "{{ item }}"
  with_items:
    - libdrm-dev
#    - xorg-dev #this is not mandatory

- name: Check if exists a groovymame installation.
  stat:
    path: "/usr/local/bin/groovymame"
  register: bin

- name: Download groovymame.
  unarchive:
    src: "https://github.com/antonioginer/GroovyMAME/releases/download/gm0288sr222d/groovymame_0288.222d_linux.tar.bz2"
    dest: /usr/local/bin
    remote_src: yes
  when:
    - bin.stat.exists == false

- name: Create mame dirs.
  file:
    path: "/home/arcade/.mame/roms"
    state: directory
    owner: arcade
    group: arcade

- name: Copy mame.ini.
  copy:
    src: "{{ role_path }}/files/etc/groovymame.ini"
    dest: "/home/arcade/.mame/mame.ini"
    owner: arcade
    group: arcade

- name: Remove mame executable.
  file:
    path: "/usr/games/mame"
    state: absent

- name: Create link.
  file:
    src: "/usr/local/bin/groovymame"
    dest: "/usr/local/bin/mame"
    state: link
