#install and configure switchres
---
- name: Install dependencies.
  apt:
    name: "libsdl2-2.0-0"

- name: Check if exists a switchres installation.
  stat:
    path: "/usr/local/bin/switchres"
  register: bin

- name: Download switchres.
  get_url:
    url: "{{ source_url }}/{{ switchresdeb }}"
    dest: "/home/switchres.deb"
    timeout: 60
  when:
    - bin.stat.exists == false

- name: Install switchres.
  apt:
    deb: "/home/switchres.deb"
  when: bin.stat.exists == false

- name: Remove deb file.
  file:
    path: "/home/switchres.deb"
    state: absent

- name: Set KMS backend by default
  lineinfile:
    dest: /etc/switchres.ini
    regexp: "^(.*)api(.*)$"
    line: "\tapi\t\t\tdrmkms"
    backrefs: yes
