---
#  - include_tasks: 00-no_install_recommends.yml
  - include_tasks: 01-users.yml
  - include_tasks: 02-autologin.yml
  - include_tasks: 03-samba.yml
  - include_tasks: 04-tweaks.yml
  - include_tasks: 05-kernel.yml
  - include_tasks: 06-sdl2.yml
  - include_tasks: 07-switchres.yml
  - include_tasks: 08-emulationstation_de.yml
  - include_tasks: 09-groovymame.yml
  - include_tasks: 10-retroarch.yml
