---
- name: Check if it's already installed.
  stat:
    path: "/usr/local/bin/emulationstation"
  register: emulationstation_bin

- name: Install attractplus build dependencies.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - build-essential
    - cmake
    - libgl1-mesa-dev
    - libfreetype-dev
    - libfreeimage-dev
    - libsdl2-dev
    - libcurl4-openssl-dev
    - libvlc-dev
  when: not emulationstation_bin.stat.exists

#https://stackoverflow.com/questions/50966777/ansible-download-latest-release-binary-from-github-repo
- name: Get latest release's tag.
  uri:
    url: https://api.github.com/repos/Retropie/EmulationStation/releases/latest
    return_content: true
  register: json_reponse
  when: not emulationstation_bin.stat.exists

- name: Download latest release from github.
  git:
    repo: 'https://github.com/RetroPie/EmulationStation'
    dest: /home/emulationstationgit
    version: "{{ json_reponse.json.tag_name  }}"
    recursive: true
  when: not emulationstation_bin.stat.exists

- name: Apply patch to multiple files under basedir
  patch:
    src: "{{ role_path }}/files/emulationstation_datasource.patch"
    basedir: "/home/emulationstationgit"
    strip: 1
  when: not emulationstation_bin.stat.exists

#- name: Build emulationstation.
#  make:
#    chdir: "/home/{{ archive_contents.files[0].split('/')[0] }}"
#    params:
#      prefix: /usr/local
#      STATIC: 1
#      FE_HWACCEL_VAAPI: 1
#      USE_DRM: 1
#  when: not emulationstation_bin.stat.exists
