---
- name: Install sdl2 library to get all the dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libsdl2-2.0-0
    - libsdl-ttf2.0-0
    - libsdl2-dev
    - libsdl2-ttf-dev

- name: Download sdl2 deb. 64 bit.
  get_url:
    url: "https://www.dropbox.com/s/bsaqfuhppzryfqj/sdl-release_2.24-1_amd64_nopatch.deb?dl=1"
    dest: "/root/sdl2.deb"
  when: ansible_architecture == 'x86_64'

- name: Download sdl2 deb. 32 bit.
  get_url:
    url: "https://www.dropbox.com/s/6ob0cff3vv2jasg/sdl-release_2.24-1_i386_nopatch.deb?dl=1"
    dest: "/root/sdl2.deb"
  when: ansible_architecture == 'i386'

- name: Install sdl2.
  apt:
    deb: "/root/sdl2.deb"

- name: Remove deb file.
  file:
    path: "/root/sdl2.deb"
    state: absent
