---
- name: Check if it's already installed
  stat:
    path: "/usr/local/bin/switchres"
  register: switchres_bin

- name: Install switchres build dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - build-essential
    - pkg-config
    - libxrandr-dev
    - libdrm-dev
    - libsdl2-dev
  when: not switchres_bin.stat.exists

- name: Download switchres git
  git:
    repo: 'https://github.com/antonioginer/switchres.git'
    dest: /home/switchres
  when: not switchres_bin.stat.exists

- name: Build switchres.
  make:
    chdir: /home/switchres
  when: not switchres_bin.stat.exists

- name: Install switchres.
  make:
    chdir: /home/switchres
    target: install
#    params:
#      NUM_THREADS: 4
  when: not switchres_bin.stat.exists

- name: copy switchres executable.
  copy:
    src: "/home/switchres/switchres"
    dest: "/usr/local/bin/switchres"
    remote_src: yes
    mode: 0755
  when: not switchres_bin.stat.exists
