---
- name: Check if it's already installed
  stat:
    path: "/usr/local/bin/switchres"
  register: switchres_bin

- name: Install switchres build dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
  when: not switchres_bin.stat.exists

- name: Download switchres git
  git:
    repo: 'https://github.com/antonioginer/switchres.git'
    dest: /home/switchres
  when: not switchres_bin.stat.exists

- name: Build switchres.
  make:
    chdir: /home/switchres

- name: Install switchres.
  make:
    chdir: /home/switchres
    target: install
#    params:
#      NUM_THREADS: 4
