#Install AdvanceMenu
---
- name: Install AdvanceMenu dependencies.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libasound2

- name: Download AdvanceMenu deb. 64 bit.
  get_url:
    url: "https://www.dropbox.com/s/p0hs7xnxvuknn4c/advmenuplus_20171123-1_amd64.deb?dl=1"
    dest: "/root/advancemenu.deb"
  when: ansible_architecture == 'x86_64'

- name: Download AdvanceMenu deb. 32 bit.
  get_url:
    url: "https://www.dropbox.com/s/ujepsxaediim4es/advmenuplus_20171123-1_i386.deb?dl=1"
    dest: "/root/advancemenu.deb"
  when: ansible_architecture == 'i386'

- name: Install AdvanceMenu.
  apt:
    deb: "/root/advancemenu.deb"

- name: Remove deb file.
  file:
    path: "/root/advancemenu.deb"
    state: absent
