#Install Attract Mode plus
---
- name: Install Attract Mode plus dependencies.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libsfml-graphics2.5
    - libcurl4
    - libavformat58
    - libswscale5
    - libopenal1

- name: Download Attract Mode plus deb. 64 bit.
  get_url:
    url: "https://www.dropbox.com/s/97hxs8mgnrstuea/attractplus_20221112-1_amd64.deb?dl=1"
    dest: "/root/attractplus.deb"
  when: ansible_architecture == 'x86_64'

- name: Download Attract Mode plus deb. 32 bit.
  get_url:
    url: "https://www.dropbox.com/s/w3bnqhfgigrd6sp/attractplus_20221112-1_i386.deb?dl=1"
    dest: "/root/attractplus.deb"
  when: ansible_architecture == 'i386'

- name: Install Attract Mode plus.
  apt:
    deb: "/root/attractplus.deb"

- name: Remove deb file.
  file:
    path: "/root/attractplus.deb"
    state: absent
