---
- name: Check if it's already installed.
  stat:
    path: "/usr/local/bin/emulationstation"
  register: emulationstation_bin

- name: Install attractplus build dependencies.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - build-essential
    - cmake
    - libgl1-mesa-dev
    - libfreetype-dev
    - libfreeimage-dev
    - libsdl2-dev
    - libcurl4-openssl-dev
    - libvlc-dev
    - rapidjson-dev
  when: not emulationstation_bin.stat.exists

#https://stackoverflow.com/questions/50966777/ansible-download-latest-release-binary-from-github-repo
- name: Get latest release's tag.
  uri:
    url: https://api.github.com/repos/Retropie/EmulationStation/releases/latest
    return_content: true
  register: json_reponse
  when: not emulationstation_bin.stat.exists

- name: Download latest release from github.
  git:
    repo: 'https://github.com/RetroPie/EmulationStation'
    dest: /home/emulationstationgit
    version: "{{ json_reponse.json.tag_name  }}"
    recursive: true
  when: not emulationstation_bin.stat.exists

- name: Apply resources patch.
  patch:
    src: "{{ role_path }}/files/emulationstation_datasource.patch"
    basedir: "/home/emulationstationgit"
    strip: 1
  when: not emulationstation_bin.stat.exists

- name: Execute cmake.
  command:
    cmd: "cmake ."
    chdir: "/home/emulationstationgit"
  when: not emulationstation_bin.stat.exists

- name: Build emulationstation.
  make:
    chdir: "/home/emulationstationgit"
  when: not emulationstation_bin.stat.exists

- name: Install emulationstation.
  make:
    chdir: "/home/emulationstationgit"
    target: install
  when: not emulationstation_bin.stat.exists

- name: Create resources dir.
  file:
    path: "/usr/share/emulationstation"
    state: directory
  when: not emulationstation_bin.stat.exists

- name: Copy resources.
  copy:
    src: "/home/emulationstationgit/resources"
    dest: "/usr/share/emulationstation"
  when: not emulationstation_bin.stat.exists

- name: Remove build dependencies.
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - build-essential
    - cmake
    - libgl1-mesa-dev
    - libfreetype-dev
    - libfreeimage-dev
    - libsdl2-dev
    - libcurl4-openssl-dev
    - libvlc-dev
    - rapidjson-dev

- name: Create package dirs.
  file:
    path: "/home/packages/emulationstation/{{ item }}"
    state: directory
  with_items:
     - usr/local/bin
     - usr/local/include
     - usr/local/lib/cmake/pugixml

- name: Copy package files.
  copy:
    src: "/home/emulationstationgit/{{ item.src }}"
    dest: "/home/packages/emulationstation/{{ item.dest }}"
    mode: 0644
    remote_src: true
  with_items:
     - { src: "libpugixml.a", dest: "usr/local/lib/libpugixml.a" }
     - { src: "external/pugixml/src/pugixml.hpp", dest: "usr/local/include/pugixml.hpp" }
     - { src: "external/pugixml/src/pugiconfig.hpp", dest: "usr/local/include/pugiconfig.hpp" }
     - { src: "external/pugixml/CMakeFiles/Export/be764272e56105fc8ff11fec8314e604/pugixml-config.cmake", dest: "usr/local/lib/cmake/pugixml/pugixml-config.cmake" }
     - { src: "external/pugixml/CMakeFiles/Export/be764272e56105fc8ff11fec8314e604/pugixml-config-noconfig.cmake", dest: "usr/local/lib/cmake/pugixml/pugixml-config-noconfig.cmake" }
     - { src: "emulationstation", dest: "usr/local/bin/emulationstation" }

#- name: Remove source code.
#  file:
#    path: "/home/emulationstationgit"
#    state: absent

