---
- name: Install mednafen to get all the dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - mednafen

- name: Download mednafen deb. 64 bit.
  get_url:
    url: "https://www.dropbox.com/s/z2i7ipjx5h6yxmt/mednafen_1.31.0-1_amd64.deb?dl=1"
    dest: "/root/mednafen.deb"
  when: ansible_architecture == 'x86_64'

- name: Download mednafen deb. 32 bit.
  get_url:
    url: "https://www.dropbox.com/s/5dql91ftcc2w9ud/mednafen_1.31.0-1_i386.deb?dl=1"
    dest: "/root/mednafen.deb"
  when: ansible_architecture == 'i386'

- name: Install mednafen.
  apt:
    deb: "/root/mednafen.deb"

- name: Remove mednafen deb file.
  file:
    path: "/root/mednafen.deb"
    state: absent

#- name: Copy configurations.
#  copy:
#    src: "{{ role_path }}/files/etc/retroarch{{ card }}.cfg"
#    dest: "/etc/retroarch.cfg"
#    mode: 0644

#- name: Copy retroarch intel script.
#  copy:
#    src: "{{ role_path }}/files/usr/local/bin/retroarch_intel"
#    dest: "/usr/local/bin/retroarch_intel"
#    mode: 0755

#- name: Copy retroarch ati script.
#  copy:
#    src: "{{ role_path }}/files/usr/local/bin/retroarch_ati"
#    dest: "/usr/local/bin/retroarch_ati"
#    mode: 0755
