---
- name: Install retroarch to get all the dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - retroarch

- name: Download retroarch deb. 64 bit.
  get_url:
    url: "https://www.dropbox.com/s/34a7orlxggvygqz/retroarch_1.12.0-1_amd64.deb?dl=1"
    dest: "/root/retroarch.deb"
  when: ansible_architecture == 'x86_64'

- name: Download retroarch deb. 32 bit.
  get_url:
    url: "https://www.dropbox.com/s/3e385r11ds327gz/retroarch_1.12.0-1_i386.deb?dl=1"
    dest: "/root/retroarch.deb"
  when: ansible_architecture == 'i386'

- name: Install retroarch.
  apt:
    deb: "/root/retroarch.deb"

- name: Remove deb file.
  file:
    path: "/root/retroarch.deb"
    state: absent
    
- name: Copy switchres.ini file.
  copy:
    src: "{{ role_path }}/files/etc/switchres.ini"
    dest: "/etc/switchres.ini"
    mode: 0644

#- name: Copy configurations.
#  copy:
#    src: "{{ role_path }}/files/etc/retroarch{{ card }}.cfg"
#    dest: "/etc/retroarch.cfg"
#    mode: 0644

#- name: Copy retroarch intel script.
#  copy:
#    src: "{{ role_path }}/files/usr/local/bin/retroarch_intel"
#    dest: "/usr/local/bin/retroarch_intel"
#    mode: 0755

#- name: Copy retroarch ati script.
#  copy:
#    src: "{{ role_path }}/files/usr/local/bin/retroarch_ati"
#    dest: "/usr/local/bin/retroarch_ati"
#    mode: 0755
