#ansible playbook to execute some roles. debootstrap will create the basic client an minimal will add some default packages and configs
#if the host in the "desktops" group will execute the desktop role too. squash will create the filesystem.squash file and delete temporary files
---
- hosts: localhost
  connection: local
  tasks:
    - name: Install required packages.
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - debootstrap
        - squashfs-tools
        - whois
        - zstd
        - dosfstools
        - grub-pc-bin
        - grub-efi-ia32-bin
        - grub-efi-amd64-bin
        - parted
        - xorriso

- hosts: all
  connection: local
  roles:
    - debootstrap

- hosts: all
  connection: chroot
  vars:
    ansible_host: "{{ inventory_hostname }}/live/squashfs-root"
  tasks:
    - include_tasks: prepare.yml
    - include_role:
        name: livecd
    - include_role:
        name: retro_compile
    - include_role:
        name: retro_install
    - include_tasks: exit.yml

- hosts: all
  connection: local
  roles:
    - squash
