#This task installs network-manager.
---
- name: Install network-manager.
  apt:
    name: "network-manager"

- name: Copy wifi configuration template.
  copy:
    src: "{{ role_path }}/files/etc/network/interfaces.d/wifi"
    dest: "/etc/network/interfaces.d"
    mode: 0644
