#!/bin/bash

cat << EOF
menuentry "Debian 15khz ATI" {
      search --no-floppy --fs-uuid --set=root {{ UUID }}
      linux   {{ vmlinuz }} root=UUID={{ UUID }} ro video=VGA-1:640x480iec
      initrd  {{ initrd }}
}
menuentry "Debian 15khz INTEL" {
      search --no-floppy --fs-uuid --set=root {{ UUID }}
      linux   {{ vmlinuz }} root=UUID={{ UUID }} ro video=VGA-1:1280x480iec
      initrd  {{ initrd }}
}
EOF
