#!/bin/bash

disks=`lsblk | grep disk | wc -l`
if [ $disks -eq 0 ]
  then
    echo "There are no disks"
    exit
fi

command=""
for i in $(seq $disks)
do
   name=$(lsblk | grep disk | awk -v line="$i" 'FNR == line {print $1}')
   size=$(lsblk | grep disk | awk -v line="$i" 'FNR == line {print $4}')
   command="${command} ${i} ${name}:${size}"
done
chose=$(whiptail --menu "Installer" 0 0 $disks $command 3>&2 2>&1 1>&3)
exitstatus=$?
if [ $exitstatus = 0 ]; then
   chosen=$(lsblk | grep disk | awk -v line="$chose" 'FNR == line {print $1}')
else
   exit
fi

#/dev/sda1 vs /dev/nvme0n1p1
p=""
if [[ $chosen = nvme* || $chosen = mmc* ]]
  then
    p="p"
fi

#set variables
if test -d "/sys/firmware/efi"; then
    echo "this is a efi system"
    partitiontable="gpt"
    firstpartition="ESP"
    grubmount="/boot/efi"
else
    echo "this is a bios system"
    partitiontable="msdos"
    firstpartition="primary"
    grubmount="/boot/grub"
fi

#umount disk
for n in /dev/$chosen* ; do umount $n ; done
swapoff --all

#get disk size
disksize=$(lsblk /dev/$chosen | grep disk | awk '{ print $4 }' | tr -d G)
nodot=${disksize%.*}
nodecimal=${nodot%,*}

if [ "$nodecimal" -gt 20 ]; then
   #create partition table
   echo "It's greater than 20GB, create home partition too"
   dd if=/dev/zero of=/dev/$chosen bs=10240 count=1 > /dev/null 2>&1
   parted -s -- /dev/$chosen mklabel $partitiontable  \
    mkpart $firstpartition fat32 0% 200MB  \
    mkpart primary ext4 200MB 20GB  \
    mkpart primary linux-swap 20GB 24GB  \
    mkpart primary ext4 24GB 100%  \
    set 1 boot on
   sync

   #format partitions
   mkfs.vfat /dev/${chosen}${p}1 -F 32 -n BOOT > /dev/null 2>&1
   mkfs.ext4 /dev/${chosen}${p}2 -FL system > /dev/null 2>&1
   mkswap /dev/${chosen}${p}3 > /dev/null 2>&1
   mkfs.ext4 /dev/${chosen}${p}4 -FL home > /dev/null 2>&1

   #get UUIDs
   uuid1=`blkid -s UUID -o value /dev/${chosen}${p}1`
   uuid2=`blkid -s UUID -o value /dev/${chosen}${p}2`
   uuid3=`blkid -s UUID -o value /dev/${chosen}${p}3`
   uuid4=`blkid -s UUID -o value /dev/${chosen}${p}4`
else
   #create partition table
   echo "It's smaller than 20GB, don't create home partition"
   dd if=/dev/zero of=/dev/$chosen bs=10240 count=1 > /dev/null 2>&1
   parted -s -- /dev/$chosen mklabel $partitiontable  \
    mkpart $firstpartition fat32 0% 200MB  \
    mkpart primary ext4 200MB -1GB  \
    mkpart primary linux-swap -1GB 100%  \
    set 1 boot on
   sync

   #format partitions
   mkfs.vfat /dev/${chosen}${p}1 -F 32 -n BOOT > /dev/null 2>&1
   mkfs.ext4 /dev/${chosen}${p}2 -FL system > /dev/null 2>&1
   mkswap /dev/${chosen}${p}3 > /dev/null 2>&1

   #get UUIDs
   uuid1=`blkid -s UUID -o value /dev/${chosen}${p}1`
   uuid2=`blkid -s UUID -o value /dev/${chosen}${p}2`
   uuid3=`blkid -s UUID -o value /dev/${chosen}${p}3`
   uuid4="none"
fi

#install system in second partition
mkdir system
mount /dev/${chosen}${p}2 system
#echo "copying the image..."
#pv /run/live/medium/live/filesystem.squashfs > system/filesystem.squashfs
echo "copying the md5 file..."
pv /run/live/medium/live/filesystem.md5 > system/filesystem.md5
echo "extracting the image..."
unsquashfs -f -d system /run/live/medium/live/filesystem.squashfs

#copy configuration files
cp /etc/retroarch.cfg system/etc/retroarch.cfg
cp /etc/switchres.ini system/etc/switchres.ini
cp /etc/default/grub system/etc/default/grub
cp /etc/profile.d/99-launcher.sh system/etc/profile.d/99-launcher.sh
rm system/etc/systemd/system/multi-user.target.wants/configurator.service

#move home dir
if [ "$uuid4" != "none" ]; then
    echo "moving home dir..."
    mkdir home
    mount /dev/${chosen}${p}4 home
    mv system/home/arcade home/arcade
    umount /dev/${chosen}${p}4
    rmdir home
fi

#install grub in first partition
echo "installing grub..."
mkdir system/proc
mkdir system/sys
mkdir -p system$grubmount
mount /dev/${chosen}${p}1 system$grubmount
mount -B /dev system/dev
mount -B /proc system/proc
mount -B /sys system/sys
if test -d "/sys/firmware/efi"; then
    mount -B /sys/firmware/efi/efivars system/sys/firmware/efi/efivars
    chroot system /usr/sbin/grub-install /dev/${chosen}${p}
    chroot system /usr/sbin/update-grub
    umount system/sys/firmware/efi/efivars
else
    chroot system /usr/sbin/grub-install /dev/${chosen}${p}
    chroot system /usr/sbin/update-grub
fi
umount system/sys
umount system/proc
umount system/dev
umount /dev/${chosen}${p}1

#generate fstab
echo "updating fstab..."
echo "UUID=$uuid1        $grubmount           vfat    defaults                0 0" > system/etc/fstab
echo "UUID=$uuid2    /                   ext4    defaults                0 0" >> system/etc/fstab
echo "UUID=$uuid3    swap        swap    defaults                0 0" >> system/etc/fstab
if [ "$uuid4" != "none" ]; then
    echo "UUID=$uuid4    /home       ext4    defaults                0 0" >> system/etc/fstab
fi

#remove livecd tweaks
echo "restoring systemd journal"
sed -i.bak 's,Storage=none,#Storage=auto,g' system/etc/systemd/journald.conf
echo "removing livecd services"
rm -R system/etc/systemd/system/ifup@.service.d
rm -R system/etc/systemd/system/networking.service.d

#umount second partition
umount /dev/${chosen}${p}2
rmdir system
