#this role will clean temporary files from a debootstraped system and compress it in a squashfs file
---
  - name: Remove temporary deb files.
    shell: /bin/rm -rf {{ inventory_hostname }}/live/squashfs-root/var/cache/apt/archives/*.deb

  - name: Remove apt lists.
    shell: /bin/rm -rf {{ inventory_hostname }}/live/squashfs-root/var/lib/apt/lists/*

  - name: Copy vmlinuz Debian
    copy:
      src: "{{ inventory_hostname }}/live/squashfs-root/vmlinuz"
      dest: "{{ inventory_hostname }}/vmlinuz"
      mode: 0644
    when: distro == 'debian'

  - name: Copy initrd Debian
    copy:
      src: "{{ inventory_hostname }}/live/squashfs-root/initrd.img"
      dest: "{{ inventory_hostname }}/initrd.img"
      mode: 0644
    when: distro == 'debian'

  - name: Copy vmlinuz Ubuntu
    copy:
      src: "{{ inventory_hostname }}/live/squashfs-root/boot/vmlinuz"
      dest: "{{ inventory_hostname }}/vmlinuz"
      mode: 0644
    when: distro == 'ubuntu'

  - name: Copy initrd Ubuntu
    copy:
      src: "{{ inventory_hostname }}/live/squashfs-root/boot/initrd.img"
      dest: "{{ inventory_hostname }}/initrd.img"
      mode: 0644
    when: distro == 'ubuntu'

  - name: Check if there are compiled packages.
    stat:
      path: "{{ inventory_hostname }}/live/squashfs-root/home/packages"
    register: packages

  - name: Copy packages
    copy:
      src: "{{ inventory_hostname }}/live/squashfs-root/home/packages"
      dest: "{{ inventory_hostname }}"
      mode: "preserve"
    when: packages.stat.exists == true

  - name: Remove packages
    file:
      path: "{{ inventory_hostname }}/live/squashfs-root/home/packages"
      state: absent

  - name: Create filesystem.squashfs file
    command:
      chdir: "{{ inventory_hostname }}/live"
      argv:
        - "/usr/bin/mksquashfs"
        - "squashfs-root"
        - "filesystem.squashfs"
#        - "-comp xz"
        - "-comp zstd -Xcompression-level 22"
  - name: Remove squashfs-root folder
    file:
      path="{{ inventory_hostname }}/live/squashfs-root"
      state=absent

  - name: Remove old md5 file.
    file:
      path: "{{ inventory_hostname }}/live/filesystem.md5"
      state: absent

  - name: Get md5 checksum.
    stat:
      path: "{{ inventory_hostname }}/live/filesystem.squashfs"
      checksum_algorithm: md5
      get_checksum: yes
    register: md5

  - name: Create md5 file.
    lineinfile:
      path: "{{ inventory_hostname }}/live/filesystem.md5"
      line: "{{ md5.stat.checksum }} /run/live/medium/live/filesystem.squashfs"
      create: "true"
