---
- name: Set release version.
  set_fact:
    release: "mame0270"

- name: Check if it's already installed.
  stat:
    path: "/usr/local/bin/groovymame"
  register: groovymame_bin

- name: Set package name.
  set_fact:
    package_name: "groovymame_{{ release | replace('mame0','') }}_{{ ansible_architecture | replace('x86_64','amd64') }}"

- name: Check if there is a package.
  stat:
    path: "/home/packages/{{ package_name }}.deb"
  register: debpackage

- name: Install groovymame build dependencies.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - build-essential
    - pkg-config
    - libsdl2-dev
    - libfontconfig-dev
    - qtbase5-dev
    - libsdl2-ttf-dev
  when: not groovymame_bin.stat.exists

- name: Download latest release from github.
  git:
    repo: 'https://github.com/antonioginer/groovymame'
    dest: /home/groovymamegit
    version: "{{ release  }}"
    recursive: true
  when: not groovymame_bin.stat.exists

- name: Build groovymame.
  make:
    chdir: "/home/groovymamegit"
  when: not groovymame_bin.stat.exists

- name: Install groovymame.
  copy:
    src: "/home/groovymamegit/mame"
    dest: "/usr/local/bin/groovymame"
    mode: "0755"
    remote_src: true

- name: Remove build dependencies.
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - git
    - build-essential
    - pkg-config
    - libsdl2-dev
    - libfontconfig-dev
    - qtbase5-dev
    - libsdl2-ttf-dev
  when: not groovymame_bin.stat.exists

- name: Remove source code.
  file:
    path: "/home/groovymamegit"
    state: absent
  when: not groovymame_bin.stat.exists

- name: Create package dirs.
  file:
    path: "/home/packages/{{ package_name }}/{{ item }}"
    state: directory
  with_items:
     - usr/local/bin
     - DEBIAN
  when: not debpackage.stat.exists

- name: Copy package files.
  copy:
    src: "/{{ item }}"
    dest: "/home/packages/{{ package_name }}/{{ item }}"
    mode: "preserve"
    remote_src: true
  with_items:
     - "usr/local/bin/groovymame"
  when: not debpackage.stat.exists

- name: Copy package's control file.
  template:
    src: "{{ role_path }}/templates/control.j2"
    dest: "/home/packages/{{ package_name }}/DEBIAN/control"
    mode: 0644
  vars:
    package_internal_name: "groovymame"
    package_version: "{{ release | replace('mame','') }}"
    package_architecture: "{{ ansible_architecture | replace('x86_64','amd64') }}" #ansible uses x86_64 debian uses amd64
    package_description: "MAME fork for CRTs"
  when: not debpackage.stat.exists

- name: Build package.
  command:
    chdir: "/home/packages"
    argv:
      - /usr/bin/dpkg-deb
      - "--build"
      - "--root-owner-group"
      - "{{ package_name }}"
  when: not debpackage.stat.exists

- name: Remove package source.
  file:
    path: "/home/packages/{{ package_name }}"
    state: absent
  when: not debpackage.stat.exists
