---
- name: Set release version.
  set_fact:
    release: "v2.11.2"

- name: Check if it's already installed.
  stat:
    path: "/usr/local/bin/emulationstation"
  register: emulationstation_bin

- name: Set package name.
  set_fact:
    package_name: "emulationstation_{{ release }}_{{ ansible_architecture | replace('x86_64','amd64') }}"

- name: Check if there is a package.
  stat:
    path: "/home/packages/{{ package_name }}.deb"
  register: debpackage

- name: Install emulationstation build dependencies.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - build-essential
    - cmake
    - libgl1-mesa-dev
    - libfreetype-dev
    - libfreeimage-dev
    - libsdl2-dev
    - libcurl4-openssl-dev
    - libvlc-dev
    - rapidjson-dev
  when: not emulationstation_bin.stat.exists

- name: Download latest release from github.
  git:
    repo: 'https://github.com/RetroPie/EmulationStation'
    dest: /home/emulationstationgit
    version: "{{ release  }}"
#    recursive: true
  when: not emulationstation_bin.stat.exists

- name: Apply resources patch.
  patch:
    src: "{{ role_path }}/files/emulationstation_datasource.patch"
    basedir: "/home/emulationstationgit"
    strip: 1
  when: not emulationstation_bin.stat.exists

- name: Execute cmake.
  command:
    cmd: "cmake ."
    chdir: "/home/emulationstationgit"
  when: not emulationstation_bin.stat.exists

- name: Build emulationstation.
  make:
    chdir: "/home/emulationstationgit"
  when: not emulationstation_bin.stat.exists

- name: Install emulationstation.
  make:
    chdir: "/home/emulationstationgit"
    target: install
  when: not emulationstation_bin.stat.exists

- name: Create resources dir.
  file:
    path: "/usr/local/share/emulationstation"
    state: directory
  when: not emulationstation_bin.stat.exists

- name: Copy resources.
  copy:
    src: "/home/emulationstationgit/resources"
    dest: "/usr/local/share/emulationstation"
  when: not emulationstation_bin.stat.exists

- name: Remove build dependencies.
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - build-essential
    - cmake
    - libgl1-mesa-dev
    - libfreetype-dev
    - libfreeimage-dev
    - libsdl2-dev
    - libcurl4-openssl-dev
    - libvlc-dev
    - rapidjson-dev
  when: not emulationstation_bin.stat.exists

- name: Remove source code.
  file:
    path: "/home/emulationstationgit"
    state: absent
  when: not emulationstation_bin.stat.exists

- name: Create package dirs.
  file:
    path: "/home/packages/{{ package_name }}/{{ item }}"
    state: directory
  with_items:
     - usr/local/bin
     - usr/local/include
     - usr/local/lib/cmake/pugixml
     - usr/local/share/emulationstation
     - DEBIAN
  when: not debpackage.stat.exists

- name: Copy package files.
  copy:
    src: "/{{ item }}"
    dest: "/home/packages/{{ package_name }}/{{ item }}"
    mode: "preserve"
    remote_src: true
  with_items:
     - "usr/local/lib/libpugixml.a"
     - "usr/local/share/emulationstation/"
     - "usr/local/include/pugixml.hpp"
     - "usr/local/include/pugiconfig.hpp"
     - "usr/local/lib/cmake/pugixml/pugixml-config.cmake"
     - "usr/local/lib/cmake/pugixml/pugixml-config-noconfig.cmake"
     - "usr/local/bin/emulationstation"
  when: not debpackage.stat.exists

- name: Copy package's control file.
  template:
    src: "{{ role_path }}/templates/control.j2"
    dest: "/home/packages/{{ package_name }}/DEBIAN/control"
    mode: 0644
  vars:
    package_internal_name: "emulationstation"
    package_version: "{{ release | replace('v','') }}" #remove the "v" character from the number
    package_architecture: "{{ ansible_architecture | replace('x86_64','amd64') }}" #ansible uses x86_64 debian uses amd64
    package_depends: "libfreeimage3, libsdl2-2.0-0, libcurl4, libvlc5, libgl1"
    package_description: "Emulator frontend"
  when: not debpackage.stat.exists

- name: Build package.
  command:
    chdir: "/home/packages"
    argv:
      - /usr/bin/dpkg-deb
      - "--build"
      - "--root-owner-group"
      - "{{ package_name }}"
  when: not debpackage.stat.exists

- name: Remove package source.
  file:
    path: "/home/packages/{{ package_name }}"
    state: absent
  when: not debpackage.stat.exists
