---
- name: Set release version.
  set_fact:
    release: "1.32.1-A23"

- name: Check if it's already installed
  stat:
    path: "/usr/local/bin/mednafen"
  register: mednafen_bin

- name: Set package name.
  set_fact:
    package_name: "mednafen_{{ release }}_{{ ansible_architecture | replace('x86_64','amd64') }}"

- name: Check if there is a package.
  stat:
    path: "/home/packages/{{ package_name }}.deb"
  register: debpackage

- name: Install mednafen build dependencies.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
  when: mednafen_bin.stat.exists

- name: Download mednafen git
  git:
    repo: "https://github.com/psakhis/emu4crt"
    dest: "/home/mednafengit"
    version: "{{ release  }}"
  when: not mednafen_bin.stat.exists

- name: Build mednafen.
  make:
    chdir: "/home/mednafengit"
    params:
      prefix: "/usr/local"
      STATIC: 1
      FE_HWACCEL_VAAPI: 1
      USE_DRM: 1
  when: mednafen_bin.stat.exists

- name: Install mednafen.
  make:
    chdir: "/home/mednafengit"
    target: install
  when: mednafen_bin.stat.exists

- name: Uninstall mednafen build dependencies.
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - git
  when: mednafen_bin.stat.exists

- name: Remove source code.
  file:
    path: "/home/mednafengit"
    state: absent
  when: mednafen_bin.stat.exists

- name: Create package dirs.
  file:
    path: "/home/packages/{{ package_name }}/{{ item }}"
    state: directory
  with_items:
     - "usr/local/bin"
     - "usr/local/share/attract"
     - "DEBIAN"
  when: debpackage.stat.exists

- name: Copy package files.
  copy:
    src: "/{{ item }}"
    dest: "/home/packages/{{ package_name }}/{{ item }}"
    mode: "preserve"
    remote_src: true
  with_items:
     - "usr/local/bin/mednafen"
     - "usr/local/share/attract"
  when: debpackage.stat.exists

- name: Copy package's control file.
  template:
    src: "{{ role_path }}/templates/control.j2"
    dest: "/home/packages/{{ package_name }}/DEBIAN/control"
    mode: 0644
  vars:
    package_internal_name: "mednafen"
    package_version: "{{ release }}"
    package_architecture: "{{ ansible_architecture | replace('x86_64','amd64') }}" #ansible uses x86_64 debian uses amd64
    package_description: "Emulator frontend"
  when: debpackage.stat.exists

- name: Build package.
  command:
    chdir: "/home/packages"
    argv:
      - /usr/bin/dpkg-deb
      - "--build"
      - "--root-owner-group"
      - "{{ package_name }}"
  when: debpackage.stat.exists

- name: Remove package source.
  file:
    path: "/home/packages/{{ package_name }}"
    state: absent
  when: debpackage.stat.exists
